FashionShoes/Controllers/CartController.cs
using FashionShoes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionShoes.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {

            if (Session["cart"] != null)
            {
                Cart cart = Session["cart"] as Cart;
                ViewBag.cart = cart.Items;
            }
            else ViewBag.cart = new List<CartItem>();
            return View();
        }
        public void Delete(int id)
        {
            if (Session["cart"] != null)
            {
                Cart cart = Session["cart"] as Cart;
                cart.delete(id);
            }
        }
        public void Reduce(int id)
        {
            if (Session["cart"] != null)
            {
                Cart cart = Session["cart"] as Cart;
                cart.Reduce(id);
                Session["cart"] = cart;
            }
        }
        public void Increase(int id)
        {
            if (Session["cart"] != null)
            {
                Cart cart = Session["cart"] as Cart;
                cart.Increase(id);
                Session["cart"] = cart;
            }
        }
    }
}

FashionShoes/Controllers/PartialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FashionShoes.Entity;

namespace DT.Controllers
{
    public class PartialController : Controller
    {
        dbFashionShoesEntities db = new dbFashionShoesEntities();
        // GET: Partial
        public ActionResult ThuongHieu()
        {
            return PartialView(db.tb_ThuongHieu);
        }
        public ActionResult ThuongHieuSideBar()
        {
            return PartialView(db.tb_ThuongHieu);
        }
        public ActionResult ThuongHieuMenu()
        {
            return PartialView(db.tb_ThuongHieu);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FashionShoes/Views/Shared/_Layout.cshtml
<!Doctype html>
<html lang="vi">
<head>
    <meta charset="utf-8">

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">

    <!-- Place favicon.ico in the root directory -->
    <!--    public-->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />


    <meta name="theme-color" content="#fafafa">
    <title>@ViewBag.Title - PhoneStore</title>

    @Styles.Render("~/bundles/bootstrap")

    @Styles.Render("~/Assets/css")

</head>

<body>
    <div class="wrapper" id="bd-wrapper">
        <header id="header" class="bg-light">
            <div class="bottom">

                @RenderPage("_Navigation.cshtml")

            </div>
        </header>
        <div class="main">
            @RenderBody()
        </div>
        <footer>
            <div class="container">
                <div class="footer-top border-bottom py-5">
                    <div class="row">
                        <div class="col-lg-3 col-sm-12">
                            <div class="logo mb-2">
                                <a href="#" class="ps-0">
                                    <img src="~/assets/img/logo_w.png" style="width:100px" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="row">
                                <div class="col-lg-3 mt-2 col-md-6">
                                    <div class="title">
                                        <h5 class="cl-gray">Giới thiệu</h5>
                                    </div>
                                    <div class="content mt-3">
                                        <p class="cl-gray">
                                            Khóa luận tốt nghiệp
                                            <br>
                                            Trang web bán giày thời trang
                                            <br>
                                            Thành viên:
                                            <br>
                                            Dương Thị Huỳnh Như
                                            <br>
                                            Huỳnh Kiến Phúc
                                        </p>
                                    </div>
                                </div>
                                <div class="col-lg-3 mt-2 col-md-6">
                                    <div class="title">
                                        <h5 class="cl-gray">Liên hệ</h5>
                                    </div>
                                    <div class="content mt-3">
                                        <div class="list-group list-group-flush">
                                            <a href="https://goo.gl/maps/CR6mRdSdT4mnvaJL9"
                                               target="_blank"
                                               class="list-group-item border-0 ps-0 bg-transparent cl-gray list-group-item-action">
                                                <i class="bi bi-geo-alt-fill"></i>
                                                140 Lê Trọng Tấn, phường Tây Thạnh, quận Tân Phú, thành phố Hồ Chí Minh
                                            </a>
                                            <a href="tel:19001602"
                                               target="_blank"
                                               class="list-group-item border-0 ps-0 bg-transparent cl-gray list-group-item-action">
                                                <i class="bi bi-telephone"></i>
                                                1900 1602
                                            </a>
                                            <a href="mailto:longmoble@gmail.com"
                                               target="_blank"
                                               class="list-group-item border-0
                                                ps-0 bg-transparent cl-gray list-group-item-action">
                                                <i class="bi bi-envelope"></i>
                                                sunkist.hutr@gmail.com
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 mt-2 col-md-6">
                                    <div class="title">
                                        <h5 class="cl-gray">Tư vấn</h5>
                                    </div>
                                    <div class="content mt-3 cl-gray">
                                        <div>
                                            <h6>Tư vấn mua hàng (Miễn phí)</h6>
                                            <div class="center-Y">
                                                <h6 class="mb-0 me-1">
                                                    <a href="tel:1900 1602" class="cl-gray">1900 1602</a>
                                                </h6>
                                                <span>(Nhánh 1)</span>
                                            </div>
                                        </div>
                                        <div class="mt-3">
                                            <h6>Hỗ trợ kỹ thuật</h6>
                                            <div class="center-Y">
                                                <h6 class="mb-0 me-1">
                                                    <a href="tel:1900 1602" class="cl-gray">1900 1602</a>
                                                </h6>
                                                <span>(Nhánh 2)</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 mt-2 col-md-6">
                                    <div class="title">
                                        <h5 class="cl-gray">Liên kết</h5>
                                    </div>
                                    <div class="content mt-3">
                                        <div class="list-group list-group-flush">
                                            <a href="/di-dong" class="list-group-item border-0 pt-0 ps-0 bg-transparent cl-gray list-group-item-action">Nữ</a>
                                            <a href="/phu-kien" class="list-group-item border-0 ps-0 bg-transparent cl-gray list-group-item-action">Nam</a>
                                            <a href="/tra-cuu-don-hang" class="list-group-item border-0 ps-0 bg-transparent cl-gray list-group-item-action">Tra cứu đơn hàng</a>
                                            <a href="/hoi-dap" class="list-group-item border-0 ps-0 bg-transparent cl-gray list-group-item-action">Hỏi đáp</a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-bottom py-4 cl-gray">
                    <div class="text-center">
                        <p class="mb-0">
                            © 2022 LIBER
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <div class="modal" id="modal" tabindex="-1" style="display:@(ViewBag.showModal == true ? "block": "none")">
            <div class="modal-dialog">
                <div class="modal-content border-0 box-side">
                    <div class="modal-header py-0 border-0">
                        <h6 class="modal-title ">Thông báo</h6>
                    </div>
                    <div class="modal-body">
                        <p class="mb-0">@ViewBag.ModalContent</p>
                    </div>
                    <div class="modal-footer border-0 py-0">
                        <button type="button" onclick="$('#modal').css('display','none')" class="my-btn py-1">Đóng</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
    <script src="~/Assets/js/swiper-bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
    <script type="module" src="~/Assets/js/sort_product.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script src="~/Scripts/fetchapi.js"></script>
    <script>$(document).ready(function () {
            let isShow = false;
            $("#toggle_menu").click(function () {
                if (!isShow) {
                    $("#icon-toggle").attr('class', 'bi bi-x');
                    $(".menu-mobile").animate({ left: '0' });
                    isShow = true;
                }
                else {
                    $("#icon-toggle").attr('class', 'bi bi-list');
                    $(".menu-mobile").animate({ left: '-100%' });
                    isShow = false;
                }
            });
        });
        AOS.init();
        const swiper = new Swiper(".mySwiper", {
            spaceBetween: 30,
            centeredSlides: true,
            autoplay: {
                delay: 2500,
                disableOnInteraction: false,
            },
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
        });
        const swiper2 = new Swiper(".mySwiper2", {
            breakpoints: {
                425: {
                    slidesPerView: 2,
                    spaceBetween: 5,
                },
                768: {
                    slidesPerView: 3,
                    spaceBetween: 10,
                },
                1024: {
                    slidesPerView: 4,
                    spaceBetween: 20,
                },
                1440: {
                    slidesPerView: 5,
                    spaceBetween: 30,
                }
            },
            freeMode: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
        });</script>

</body>
</html>

FashionShoes/Views/Shared/_Navigation.cshtml
@using FashionShoes.Entity.DAO
@using FashionShoes.Models
@{ Cart cart;
                if (Session["cart"] != null)
                {
                    cart = Session["cart"] as Cart;
                }
                else
                {
                    cart = new Cart();
                } }
<nav class="navbar py-0 px-md-5 navbar-expand-lg navbar-light" id="navbar">
    <div class="px-lg-5 w-100 d-flex wrap-menu">
        <a class="navbar-brand logo" href="/">
            <img src="~/assets/img/logo.gif" alt="funny GIF" style="width:80px" alt="logo">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 my-navbar">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Trang Chủ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/gioitinh-nu">Nữ</a>
                    <div class="sub-navigation">
                        <div class="container-fluid p-5">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="header between">
                                        <div class="left">
                                            <h3>Nữ</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-8">
                                    <div class="site-menu">
                                        <ul class="sub-nav">
                                            @Html.Action("ThuongHieuMenu", "Partial")

                                        </ul>
                                    </div>
                                </div>
                                <div class="col-4 border-start">
                                    <div class="card border-0" style="width: 20rem;">
                                        <img src="~/assets/img/HOME_COMBO_KV_GNB_624X624.jpg" class="card-img-top" alt="...">
                                        <div class="card-body ps-0">
                                            <h5 class="card-title">Galaxy Z Fold</h5>
                                            <a href="#" class="nav-link ps-0">Tìm hiểu thêm</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/gioitinh-nam">Nam</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sale-up">SaleUp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/tra-cuu-don-hang">Tra cứu đơn hàng</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/lien-he">Liên Hệ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/hoi-dap">Hỏi Đáp</a>
                </li>
            </ul>
        </div>
        <div class="menu-control center">
            <ul class="navbar-nav flex-row nav-icon">
                <li class="nav-item drop_menu search position-relative center">
                    <i class="bi bi-search"></i>
                    <div class="bg-transparent border-0 drop_down">
                        <form action="/san-pham" method="get">
                            <div class="input-group">
                                <input type="text" placeholder="Tìm kiếm" name="p" class="form-control">
                                <button type="submit" class="btn btn-secondary">
                                    <i class="bi bi-search"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                </li>
                <li class="nav-item drop_menu position-relative center cart-AKAIJI">
                    <i class="bi bi-bag"></i>
                    <div class="bg-white cart-menu drop_down">
                        <div class="card border rounded-0 bg-transparent">
                            <div class="card-header pt-3 bg-transparent">
                                <h6>Giỏ hàng của bạn</h6>
                            </div>
                            <div class="card-body cart">
                                @{ if (cart.Items.Count() > 0)
                                                {

                                                    foreach (CartItem item in cart.Items)
                                                    {
                                    <div class="item-cart" id="cartItem_e_@item.ProductID">
                                        <div class="single-image" style="width:70px">
                                            <img src="~/assets/img/img_downloaded/@item.ImageUrl" alt="@item.ProductName">
                                        </div>
                                        <div class="text me-auto">
                                            <h6 class="name-product">
                                                @item.ProductName
                                            </h6>
                                            <span>@item.Quantity x @string.Format("{0:C}", item.Price).Replace("$", "").Replace(".00", "") VNĐ</span>
                                        </div>
                                        <div class="remove-item">

                                            @Ajax.ActionLink(" ", "Delete", "Cart", new { @id = item.ProductID }, new AjaxOptions
                                            {
                                                Confirm = "Bạn có muốn xóa sản phẩm này khỏi giỏ hàng không",
                                                OnComplete = "$('#cartItem_e_" + @item.ProductID + "').remove()",
                                                HttpMethod = "Delete"

                                            }, new { @class = "bi bi-x-circle text-black" })
                                        </div>
                                    </div> }
                                                }
                                                else
                                                {
                                    <div class="text-center">
                                        <h6>Giỏ hàng trống</h6>
                                    </div> } }
                            </div>
                            @if (cart.Items.Count() > 0)
                            {
                <div class="card-footer between bg-white py-3">
                    <a href="/gio-hang" class="my-btn py-2 px-3">Xem giỏ hàng</a>
                    <a href="/thanh-toan" class="my-btn mybtn-out py-2 px-3">Thanh toán</a>
                </div>}
                        </div>
                    </div>
                </li>
                <li class="btn icon-menu btn-mobile" id="toggle_menu">
                    <i id="icon-toggle" class="bi bi-list"></i>
                </li>
            </ul>
        </div>
        <div class="menu-mobile">
            <ul class="navbar-nav flex-column me-auto mb-2 mb-lg-0 my-navbar">
                <li class="nav-item">
                    <span>
                        <a class="nav-link active" aria-current="page" href="/">Trang Chủ</a>
                    </span>
                </li>
                <li class="nav-item">
                    <span class="between">
                        <a class="nav-link" href="/sex-nu">Nữ</a>
                        <i class="bi bi-plus"></i>
                    </span>
                    <ul class="menu-child">
                        @Html.Action("ThuongHieu", "Partial");
                    </ul>
                </li>
                <li class="nav-item">
                    <span class="between">
                        <a class="nav-link" href="/nam">Nam</a>
                    </span>
                </li>
                <li class="nav-item">
                    <span>
                        <a class="nav-link" href="/tra-cuu-don-hang">Tra cứu đơn hàng</a>
                    </span>
                </li>
                <li class="nav-item">
                    <span>
                        <a class="nav-link" href="/lien-he">Liên Hệ</a>
                    </span>
                </li>
                <li class="nav-item">
                    <span>
                        <a class="nav-link" href="/hoi-dap">Hỏi Đáp</a>
                    </span>
                </li>
                <li class="nav-item border-top">
                    <span>
                        <a class="nav-link" href="/gio-hang">Giỏ hàng</a>
                    </span>
                </li>
                <li class="nav-item">
                    <span>
                        <a class="nav-link" href="/thanh-toan">Thanh Toán</a>
                    </span>
                </li>
            </ul>
        </div>
    </div>
</nav>

FashionShoes/Views/Shared/_Pagination.cshtml
@{ var crPage = ViewBag.crPage;
    var totalPage = ViewBag.totalPage;
    var p = ViewBag.p;
    var paramSearch = "";
    if (p != null)
    {
        paramSearch = "&p=" + p;
    } }
@if (totalPage > 1)
{
<div class="row">
    <div class="col-12">
        <div class="box-side">
            <nav aria-label="Page navigation example">
                <ul class="pagination">

                    @if (crPage != 1 && crPage - 2 > 1)
                    {
    <li class="page-item">
        <a class="page-link" href="@("?page=1"+paramSearch)" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
                        <li class="page-item"><span class="page-link text-black">...</span></li>}
                    @for (int i = 0; i < totalPage; i++)
                    {
                        var page = i + 1;

                        if (crPage == page)
                        {
    <li class="page-item"><span class="page-link bg-black text-white">@page</span></li> }
                        else
                        {
                            if (page > crPage - 3 && page < crPage + 3)
                            {
    <li class="page-item"><a class="page-link" href="?page=@page@paramSearch">@page</a></li>}
                        }
                    }
                    @if (crPage != totalPage && crPage + 2 < totalPage)
                    {
    <li class="page-item"><span class="page-link text-black">...</span></li>
                        <li class="page-item">
                            <a class="page-link" href="?page=@totalPage@paramSearch" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>}
                </ul>
            </nav>
        </div>
    </div>
</div>}

FashionShoes/Views/Shared/_SideBar.cshtml
@using FashionShoes.Entity.DAO
<div class="col-lg-3">
    <div class="row">
        <div class="col-lg-12 col-md-6">
            <div class="box-side">
                <div class="title p-0 py-2 border-bottom">
                    <h6 class="m-0">Thể loại</h6>
                </div>
                <div class="content pt-2">
                    <ol class="list-group list-group-flush list-group-numbered">
                        @Html.Action("ThuongHieuSideBar", "Partial")
                        <li class="list-group-item ps-0 d-flex justify-content-between border-0 align-items-start">
                            <div class="ms-2 me-auto">
                                <span>
                                    <a href="/gioitinh-nam" class="nav-link text-black p-0">Nam</a>
                                </span>
                            </div>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="col-lg-12 qc col-md-6">
            <div class="box-side">
                <a href="https://www.fuzebev.com/products" target="_blank"><img src="~/Assets/img/sidebar01.jpg" /></a>
            </div>
        </div>
        <div class="col-lg-12 qc col-md-6">
            <div class="box-side">
                <a href="https://www.pepsi.com/en-us/" target="_blank">
                    <img src="~/Assets/img/sidebar02.jpg" />
                </a>
            </div>
        </div>
    </div>
</div>